INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @twit2poo: ibm https://t.co/dNRCGuhoRm https://t.co/W9YF0DVmc6',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @developerWorks: NEW VIDEO: This pre-recorded webcast features experts from @UNHumanRights, @RedCross, @linuxfoundation, and @NEA discus…',0.13636363636363635,0.45454545454545453);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @twit2poo: ibm https://t.co/2iwOwLiEzt https://t.co/PsFCEzVjiO',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @AI__TECH: IBM Pits Computer Against Human Debaters https://t.co/kG1HMtkReV #AI https://t.co/syM4xuLLqA',0.0,0.1);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBM: This #AI-powered assistant is embarking on a mission to join astronauts on the International @Space_Station. Meet #CIMON: the Crew…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @developerWorks: NEW VIDEO: This pre-recorded webcast features experts from @UNHumanRights, @RedCross, @linuxfoundation, and @NEA discus…',0.13636363636363635,0.45454545454545453);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @twit2poo: ibm #devicemanagement https://t.co/zDpCq8LMhn https://t.co/JTDWrSmu7j',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @developerWorks: NEW VIDEO: This pre-recorded webcast features experts from @UNHumanRights, @RedCross, @linuxfoundation, and @NEA discus…',0.13636363636363635,0.45454545454545453);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','@jmspool My team is hiring UX Researchers in NYC and San Francisco. We are a small team of fun and supportive resea… https://t.co/est2pHneKf',0.18333333333333335,0.5333333333333333);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Parmi les plus fortes hausses du jour, Verizon a gagné 3,1% et IBM s\'est adjugé 1,9%.',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @NataliaOropezaG: Inspiring workshop with our #charteroftrust partner in Geneva this week!
Great working atmosphere with @TheAESCorp @Al…',0.7125,0.875);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Decision Conversations Decoded https://t.co/I1ldEKH1p8 #IBMDigitalCharge https://t.co/Y5qc0eZP20 https://t.co/dH7oNbdY1i',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Yeh baby! Come to my state! #weready #ibm #PTECH https://t.co/mB76SHYGOD',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBM: #IBMWatson intelligently distributes renewable energy to a network of batteries, helping balance the grid. https://t.co/ivJjeoi9DS',0.8,0.9);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @chappa_shibu: 緊張して無意識にibmだしちゃうケイともう普通に見えてるカイ https://t.co/LBylWUADZ8',0.0,0.0);




INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',6,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',7,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',13,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PITS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','COMPUTER',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AGAINST',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HUMAN',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEBATERS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AI',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THIS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ASSISTANT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EMBARKING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ON',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MISSION',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','JOIN',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ASTRONAUTS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTERNATIONAL',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MEET',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CIMON',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEVICEMANAGEMENT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PARMI',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LES',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PLUS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FORTES',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HAUSSES',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DU',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','JOUR',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VERIZON',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GAGNÉ',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ET',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ADJUGÉ',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DECISION',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CONVERSATIONS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DECODED',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMDIGITALCHARGE',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','YEH',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BABY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','COME',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','STATE',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WEREADY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PTECH',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','緊張して無意識にIBMだしちゃうケイともう普通に見えてるカイ',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',5,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEVELOPERWORKS',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NEW',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VIDEO',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THIS',4,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WEBCAST',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FEATURES',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EXPERTS',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FROM',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UNHUMANRIGHTS',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','REDCROSS',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LINUXFOUNDATION',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AND',5,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NEA',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','JMSPOOL',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TEAM',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HIRING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UX',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RESEARCHERS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IN',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NYC',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SAN',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FRANCISCO',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ARE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SMALL',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OF',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FUN',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SUPPORTIVE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NATALIAOROPEZAG',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INSPIRING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WORKSHOP',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WITH',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OUR',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CHARTEROFTRUST',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PARTNER',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GENEVA',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WEEK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GREAT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WORKING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ATMOSPHERE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THEAESCORP',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMWATSON',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTELLIGENTLY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DISTRIBUTES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RENEWABLE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ENERGY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NETWORK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BATTERIES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HELPING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BALANCE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GRID',1,1);

INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','AI is everywhere. The world’s first AI - powered companion in space. #ibmisdl @IbmIndia https://t.co/vpgPZatwK5',0.25,0.3333333333333333);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Way of looking at life matters - a good quote from Albert Einstein. #ibmisdl @IbmIndia https://t.co/kOoXtiEX4Y',0.7,0.6000000000000001);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: IBM Data Science Experience demo and tutorial videos (18 videos at one place): https://t.co/5QJQwbIEjS. #ibmisdl @IbmInd…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @VAK_305: Looking to opportunities to boost your career. Have you looked at cyber security #securitycareers #ibmsecurity #ibmindia https…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','PowerAI Vision won the First place in 2Q 2018 Agile Awards. Congratulations to the entire team #powerai. #ibmisdl… https://t.co/JUE6X9RjAH',0.25,0.5694444444444444);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: June 2018 - The Green500\'s energy-efficient supercomputers. #ibmisdl  @IbmIndia https://t.co/Jf3XdrNYcK',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: Great stuff. IBM AI Learns the Art of Debate. #ibmisdl @IbmIndia https://t.co/CCpXnHPSkT',0.8,0.75);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: Great refresher. Thanks for sharing. #ibmisdl @IbmIndia https://t.co/38zYZMYQtY',0.5,0.475);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: IBM Data Science Experience demo and tutorial videos (18 videos at one place): https://t.co/5QJQwbIEjS. #ibmisdl @IbmInd…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: Attitude matters! Good view on fixed and growth mindset. #ibmisdl @IbmIndia https://t.co/YzReNVoEu5',0.39999999999999997,0.4);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','June 2018 - The Green500\'s energy-efficient supercomputers. #ibmisdl  @IbmIndia https://t.co/Jf3XdrNYcK',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Women empowerment - \'There\'s nothing women can\'t do\'. #ibmisdl  @IbmIndia https://t.co/mAiV0nmlMK',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','#IBMIndia re-jigs fresher hiring strategy in its quest for talent https://t.co/jlYGEwnjk0 https://t.co/6LHqIDV3VX',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @sailajareddyk: I agree. Each women will be having unique challenges. One should root-cause and work for possible solution. It\'s also im…',0.1875,1.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @AnandHaridass: IBM bets big on artificial intelligence for server business - The Economic Times https://t.co/ZOssHM16j2 via @economicti…',-0.13333333333333333,0.43333333333333335);




INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SAILAJAREDDYK',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DATA',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SCIENCE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EXPERIENCE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEMO',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AND',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TUTORIAL',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VIDEOS',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AT',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ONE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PLACE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',7,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMISDL',5,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LOOKING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OPPORTUNITIES',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BOOST',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','YOUR',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CAREER',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HAVE',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','YOU',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LOOKED',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CYBER',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SECURITY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SECURITYCAREERS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMSECURITY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMINDIA',5,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','JUNE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SUPERCOMPUTERS',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WOMEN',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EMPOWERMENT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NOTHING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CA',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DO',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FRESHER',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HIRING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','STRATEGY',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IN',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ITS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','QUEST',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TALENT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ANANDHARIDASS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BETS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BIG',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ON',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ARTIFICIAL',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTELLIGENCE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SERVER',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BUSINESS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ECONOMIC',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TIMES',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VIA',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AI',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EVERYWHERE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',4,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WORLD',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FIRST',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','POWERED',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','COMPANION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IN',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SPACE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMISDL',5,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMINDIA',5,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',6,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WAY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OF',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LOOKING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LIFE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MATTERS',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GOOD',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','QUOTE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FROM',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ALBERT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EINSTEIN',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','POWERAI',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VISION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WON',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PLACE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AGILE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AWARDS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CONGRATULATIONS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ENTIRE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TEAM',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',4,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SAILAJAREDDYK',4,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GREAT',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','STUFF',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LEARNS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ART',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEBATE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','REFRESHER',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THANKS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SHARING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ATTITUDE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VIEW',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ON',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FIXED',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AND',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GROWTH',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MINDSET',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AGREE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EACH',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WOMEN',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WILL',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HAVING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UNIQUE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CHALLENGES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ONE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SHOULD',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WORK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','POSSIBLE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SOLUTION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ALSO',1,1);

INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBMNews: Project CIMON, an AI assistant powered by @IBMWatson, is heading into space tomorrow to assist the crew with daily tasks aboar…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBM: #IBMWatson intelligently distributes renewable energy to a network of batteries, helping balance the grid. https://t.co/ivJjeoi9DS',0.8,0.9);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Now isn’t this amazing! #ibm #whatwedo #makeadifference #ibmwatson #watchuswork https://t.co/RhBhxufc8a',0.7500000000000001,0.9);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','@arlemi @IBMWatson Hey thanks for the reply!

It turns out it was a weird edge case issue for folks upgrading from… https://t.co/WAaTLVf7WP',-0.125,0.6);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','With power comes responsiblity, responsibility to unblock true progress. #ResponsibleBusiness https://t.co/wrRCeaO4gR',0.35,0.65);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @DrMorey1: #China looks to #AI to save #Healthcare system #technology #MachineLearning @IBMWatson
#IBM #Watson

https://t.co/tccpU57DLV',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBMWatson: This #AI-powered assistant is embarking on a mission tomorrow to join astronauts on the International @Space_Station. Meet #…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBMNews: Project CIMON, an AI assistant powered by @IBMWatson, is heading into space tomorrow to assist the crew with daily tasks aboar…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @astro_cimon: Want to watch me 🤖 roaring into Space🚀? Read more: NASA Television to Air Launch of Next Space Station Resupply Mission #C…',0.25,0.25);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBMWatson: Interested in virtual reality gaming? By using Watson\'s Speech to Text and SDK for Unity, @RedStorm enhanced the user experi…',0.25,0.5);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @IBMNews: Project CIMON, an AI assistant powered by @IBMWatson, is heading into space tomorrow to assist the crew with daily tasks aboar…',0.0,0.0);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','RT @russelljohns: Carla Arend, IDC drilling deep into the digital organisation and multi-cloud at the Cloud&amp;Data Summit, essential for AI a…',0.0,0.2333333333333333);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Interested in virtual reality gaming? By using Watson\'s Speech to Text and SDK for Unity, RedStorm enhanced the use… https://t.co/wR9r2XKTHr',0.25,0.5);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','Interested in virtual reality gaming? By using Watson\'s Speech to Text and SDK for Unity, RedStorm enhanced the use… https://t.co/qmMZjG9FTY',0.25,0.5);


INSERT INTO twitter_sentimental_analysis (company_code, tweet, polarity, subjectivity) values ('IBM','#China looks to #AI to save #Healthcare system #technology #MachineLearning @IBMWatson
#IBM #Watson

https://t.co/tccpU57DLV',0.0,0.0);




INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',6,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMNEWS',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PROJECT',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CIMON',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AN',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AI',6,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ASSISTANT',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','POWERED',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BY',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMWATSON',6,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IS',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HEADING',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTO',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SPACE',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TOMORROW',4,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',8,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ASSIST',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',6,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CREW',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WITH',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DAILY',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TASKS',3,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CHINA',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LOOKS',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SAVE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HEALTHCARE',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SYSTEM',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TECHNOLOGY',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MACHINELEARNING',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WATSON',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THIS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EMBARKING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ON',2,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MISSION',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','JOIN',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ASTRONAUTS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTERNATIONAL',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MEET',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RUSSELLJOHNS',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CARLA',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AREND',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IDC',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DRILLING',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DEEP',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DIGITAL',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ORGANISATION',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AND',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CLOUD',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AMP',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DATA',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SUMMIT',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ESSENTIAL',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',1,0);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ARLEMI',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMWATSON',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HEY',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THANKS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',2,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','REPLY',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IT',2,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TURNS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OUT',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WAS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WEIRD',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','EDGE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','CASE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ISSUE',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOLKS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UPGRADING',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',1,-1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RT',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBM',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IBMWATSON',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTELLIGENTLY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','DISTRIBUTES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RENEWABLE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ENERGY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TO',7,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NETWORK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','OF',2,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BATTERIES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HELPING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BALANCE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THE',4,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GRID',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','HTTPS',5,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NOW',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ISN',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','THIS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AMAZING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WHATWEDO',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MAKEADIFFERENCE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WATCHUSWORK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WITH',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','POWER',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','COMES',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RESPONSIBLITY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RESPONSIBILITY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UNBLOCK',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TRUE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','PROGRESS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RESPONSIBLEBUSINESS',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WANT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WATCH',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ME',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ROARING',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTO',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','READ',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MORE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NASA',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TELEVISION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AIR',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','LAUNCH',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','NEXT',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SPACE',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','STATION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','RESUPPLY',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','MISSION',1,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','INTERESTED',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','IN',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','VIRTUAL',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','REALITY',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','GAMING',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','BY',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','USING',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','WATSON',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SPEECH',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','TEXT',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','AND',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','SDK',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','FOR',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','UNITY',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','REDSTORM',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','ENHANCED',3,1);


INSERT INTO WORD_MAP(COMPANY_CODE, WORD, COUNT, POLARITY) VALUES ('IBM','USER',1,1);